version:  "3.9"

services:
  wordpress:
    restart: always
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - ":9000"
    volumes:
      - /home/tbraquem/data/wordpress:/var/www/html
    networks:
      - inception-net
      - inception-net2

  nginx:
    restart: always
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - /home/tbraquem/data/wordpress:/var/www/html
    networks:
      - inception-net
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}

  mariadb:
    restart: always
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - ":3306"
    networks:
      - inception-net2
    volumes:
      - /home/tbraquem/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

networks:
  inception-net:
  inception-net2:
